### ISSUE TITLE
How to get the url to the already uploaded image

### ISSUE THREAD

**Issue by YuriyPrudnikov** [CTOlet/yii2-attachments#73]
Hello! How to get image url? The getUrl method is not appropriate, as it does not return the absolute path to the image)

**Comment by dmkdesign** [comment]
I believe this is not possible in the way you are thinking.  "Attachments" protects the url route to the storage location using a fileController.  The storage location is also hashed to improve file retrieval speed.  So really the "file" is retrieved using $response->sendFile().  I have added the ability to get the file "inline" instead of by downloading by using $file->getUrl($inline=true). As well, if you use getUrl in an image tag it works as intended.
